version: '2'
services:
  git-money:
    container_name: git-money
    build: git-money
    image: jcsmesquita/git-money
    working_dir: /root/git-money
    env_file:
    - ./gitmoney.env
    command: tail -f /dev/null
    links:
    - git-money-server
  git-money-server:
    container_name: git-money-server
    build: git-money
    image: jcsmesquita/git-money
    working_dir: /root/git-money
    env_file:
      - ./gitmoney.env
    command: gitmoney --init
    expose:
      - 3080
